### ISSUE TITLE
vivaldi: problem to open the options

### ISSUE THREAD

**Issue by franco27** [flyhaozi/Quick-Bookmarks-Menu#2]
with a right click on the icon . options do not open, with the Vivaldi web browser (chrome based)

**Comment by flyhaozi** [comment]
Sorry for the problem. It seems that Vivaldi and some other browsers does not support extensions' context menu yet. 
In fact, putting options in extensions' context menu is not a popular practice. I will try to move options to the popup ui in the next version to achieve better compatibility across browsers. 
I am really busy in the next days and I will finish it in late June. You can use other bookmarks extensions first. I believe there are some good alternatives in the chrome store.

**Comment by franco27** [comment]
Thank you for your reply

**Comment by flyhaozi** [comment]
Options will be in the popup menu in the next release.
